global: "{cc: gcc, cxx: g++}"
  cc_flags: # [Wall, O3]

  cxx_flags: # [Wall, O3] 
    windows:
      - s
  include_path:
    linux:
      - "/usr/include/freetype2"
      - /usr/include/freetype2/freetype
    windows:
      - "C:/VulkanSDK/$ANY/"
      - "C:/freetype"
  src_dir: src/
  build_dir: build/
  project_name: deng

tasks:
  # libsurface library
  libsurface:
    type: dynamic_lib
    src:
      - surface/key_translation.c
      - surface/key_vector.c
      - surface/vulkan_handler.c
      - surface/x11_surface.c
    
  # libdas library
  libdas:
    type: dynamic_lib
    src:
      - das/das_handler.c
      - das/data_loader.c

  # libcommon library
  libcommon:
    type: dynamic_lib
    src:
      - common/common.c

  # DENG asset manager
  dam:
    type: exec
    src:
      - dam.c
    deps:
      - ldas
      - lcommon
  
  deng:
    type: exec
    src:
      - main/sandbox.cpp
      - core/camera.cpp
      - core/rend_helpers.cpp
      - core/renderer.cpp
      - core/window.cpp
      - deng_math.cpp
      - events.cpp
      - utilities/font.cpp
    deps:
      - ldas
      - lsurface
      - lcommon
      - lfreetype
      linux:
        - lvulkan
        - lX11
        - lXcursor
        - ldl
      windows:
        - lcomctl32
        - "lvulkan1"