#ifndef MAKE_WRITER_H
#define MAKE_WRITER_H

// Makefile beginning comments
#define APPLE_PLATFORM_COMMENT      "# Platform: MacOS\n"
#define LINUX_PLATFORM_COMMENT      "# Platform: Linux\n"
#define WINDOWS_PLATFORM_COMMENT    "# Platform: Windows\n"
#define START_COMMENT               "# This makefile is is autogenerated by saucer\n"
#define MOD_COMMENT                 "# Modifying the makefile can break it, use autogeneration for it\n"
#define GIT_PAGE_COMMENT            "# Github: https://github.com/inugami-dev64/saucer\n"

// Makefile variable names
#define C_COMPILER_VAR      "CC"
#define CPP_COMPILER_VAR    "CXX"
#define SRC_DIR_VAR         "SRC_DIR"
#define BUILD_DIR_VAR       "BUILD_DIR"
#define C_FLAGS_VAR         "CC_FLAGS"
#define CPP_FLAGS_VAR       "CXX_FLAGS"
#define INCLUDE_PATH_VAR    "INCL_PATH"
#define LIBRARY_PATH_VAR    "LIB_PATH"

// Precompilation tasks
#define INIT_TASK           "." \
                            SCRIPT_NAME

#define CPY_TASK            ".cpy"
#define LINK_TASK           ".link"

// Multiline variable flags (based on gcc)
#define INCLUDE_FLAG            " -I"
#define LIBRARY_FLAG            " -L"

#ifdef MAKE_WRITER_PRIVATE
    // Main makefile writer functions 
    static void sauFindLibTargets(BuildInfo *p_bi);
    static void sauWritePremake(BuildInfo *p_bi, FILE *file);
    static void sauGetObjectFileNames(TaskInfo *p_task);
    static void sauWriteTaskTargetVar(PlatformInfo pi, TaskInfo *p_task, char *project_name, FILE *file);
    static void sauWriteTaskObjVar(PlatformInfo pi, TaskInfo *p_task, FILE *file);
    
    // Task writers
    static void sauWriteInitTask(PlatformInfo pi, FILE *file);
    static void sauWriteAllTask(TaskInfo *tasks, int32_t task_c, FILE *file);
    static void sauWriteTask(TaskInfo *p_task, PlatformInfo pi, FILE *file);
    static void sauWriteSubtask(char *obj, char *src, TargetType tar_type, PlatformInfo pi, FILE *file);
    static void sauWriteMainTask(TaskInfo *p_task, int32_t c_src_c, int32_t cxx_src_c, char *target, char *objs, PlatformInfo pi, FILE *file);
    static void sauWriteCopyTask(CopyInfo *p_cpy_info, PlatformInfo pi, char *pr_name, FILE *file);
    static void sauWriteLinkTask(LinkInfo *p_cpy_info, PlatformInfo pi, char *pr_name, FILE *file);
    static void sauWriteClean(TaskInfo *tasks, int32_t task_c, PlatformInfo pi, char *pr_name, FILE *file);

    // Platform specific functions
    static uint8_t sauWriteLibraryPathVar(char **all_str, int32_t all_str_c, char **pl_str, int32_t pl_str_c, BuildInfo *p_bi, FILE *file);
    static uint8_t sauWritePlatformFlagVar(char **all_str, int32_t all_str_c, char **pl_str, int32_t pl_str_c, char *var_name, FILE *file);
    static uint8_t sauWritePlatformMultilineVar(char **all_str, int32_t all_str_c, char **pl_str, int32_t pl_str_c, char *var_name, char *fl, FILE *file);
    static void sauGetPlatformSpecificObjNames(char **srcs, int32_t src_c, char ***p_objs, int32_t *p_obj_c, char *target_name);
    static char* sauGetPlatformSpecificDependencies(TaskInfo *p_task, PlatformInfo pi);

    // Helper functions
    static void sauPushDefaultLibraryPath(BuildInfo *p_bi, char ***p_arr, int32_t *p_arr_len);
    static void sauFixWindowsPaths(char **paths, int32_t path_c);
    static void sauCountSrcTypes(char **srcs, int32_t src_c, int32_t *p_c_src_c, int32_t *p_cxx_src_c);

    // Universal variable writer functions
    static void sauWriteSingleLineVar(char *var, char *var_val, FILE *file);
    static void sauWriteFlagsVar(char *var, char **flags, int32_t flag_c, FILE *file);
    static void sauWriteMultiLineVar(char *var, char *flag, char **var_vals, int32_t val_c, FILE *file);
#endif

void sauWriteMakefile(BuildInfo *p_bi);

#endif